/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Finnhub API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package hu.mobillab.stocksapp.model

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Get general information of a company
 * @property country Country of company&#39;s headquarter
 * @property currency Currency used in company filings
 * @property exchange Listed exchange
 * @property name Company name
 * @property ticker Company symbol/ticker as used on the listed exchange
 * @property ipo IPO date
 * @property marketCapitalization Market Capitalization
 * @property shareOutstanding Number of oustanding shares
 * @property logo Logo image
 * @property phone Company phone number
 * @property weburl Company website
 * @property finnhubIndustry Finnhub industry classification
 */
@JsonClass(generateAdapter = true)
data class CompanyProfile(
    @Json(name = "country") @field:Json(name = "country") var country: String? = null,
    @Json(name = "currency") @field:Json(name = "currency") var currency: String? = null,
    @Json(name = "exchange") @field:Json(name = "exchange") var exchange: String? = null,
    @Json(name = "name") @field:Json(name = "name") var name: String? = null,
    @Json(name = "ticker") @field:Json(name = "ticker") var ticker: String? = null,
    @Json(name = "ipo") @field:Json(name = "ipo") var ipo: String? = null,
    @Json(name = "marketCapitalization") @field:Json(name = "marketCapitalization") var marketCapitalization: Double? = null,
    @Json(name = "shareOutstanding") @field:Json(name = "shareOutstanding") var shareOutstanding: Double? = null,
    @Json(name = "logo") @field:Json(name = "logo") var logo: String? = null,
    @Json(name = "phone") @field:Json(name = "phone") var phone: String? = null,
    @Json(name = "weburl") @field:Json(name = "weburl") var weburl: String? = null,
    @Json(name = "finnhubIndustry") @field:Json(name = "finnhubIndustry") var finnhubIndustry: String? = null
)
