/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Finnhub API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package hu.mobillab.stocksapp.model

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Symbol data
 * @property description Symbol description
 * @property displaySymbol Display symbol name
 * @property symbol Unique symbol used to identify this symbol used in /stock/candle endpoint
 * @property type Security type
 */
@JsonClass(generateAdapter = true)
data class Symbol(
    @Json(name = "description") @field:Json(name = "description") var description: String? = null,
    @Json(name = "displaySymbol") @field:Json(name = "displaySymbol") var displaySymbol: String? = null,
    @Json(name = "symbol") @field:Json(name = "symbol") var symbol: String? = null,
    @Json(name = "type") @field:Json(name = "type") var type: String? = null
)
