/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Finnhub API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package hu.mobillab.stocksapp.model

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Unauthorized
 * @property error Error message
 */
@JsonClass(generateAdapter = true)
data class UnauthorizedError(
    @Json(name = "error") @field:Json(name = "error") var error: String? = null
)
